import { GlobalTire, FleetUnit } from "./types";

// Fleet units for assignment
export const fleetUnits: FleetUnit[] = [
  { id: "T-01", numero_economico: "T-01", tipo: "tractocamion" },
  { id: "T-02", numero_economico: "T-02", tipo: "tractocamion" },
  { id: "T-03", numero_economico: "T-03", tipo: "tractocamion" },
  { id: "T-04", numero_economico: "T-04", tipo: "tractocamion" },
  { id: "T-05", numero_economico: "T-05", tipo: "tractocamion" },
  { id: "R-01", numero_economico: "R-01", tipo: "remolque" },
  { id: "R-02", numero_economico: "R-02", tipo: "remolque" },
  { id: "R-03", numero_economico: "R-03", tipo: "remolque" },
  { id: "D-01", numero_economico: "D-01", tipo: "dolly" },
];

// Mock tire brands
export const tireBrands = [
  "Michelin",
  "Bridgestone",
  "Goodyear",
  "Continental",
  "Pirelli",
  "Hankook",
  "Yokohama",
];

// Mock tire inventory data
export const mockGlobalTires: GlobalTire[] = [
  {
    id: "LL-001",
    codigoInterno: "LL-001",
    marca: "Michelin",
    modelo: "X Line Energy D",
    medida: "295/80R22.5",
    dot: "2523",
    unidadActual: "T-01",
    posicion: "Eje 1 Izquierda",
    estado: "usado",
    estadoFisico: "buena",
    profundidadActual: 12,
    profundidadOriginal: 18,
    kmRecorridos: 85000,
    fechaCompra: new Date("2023-06-15"),
    precioCompra: 8500,
    costoAcumulado: 9200,
    proveedor: "Llantas del Norte S.A.",
    historial: [
      {
        id: "h1",
        fecha: new Date("2023-06-15"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 8500,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2023-06-20"),
        tipo: "montaje",
        descripcion: "Montaje en T-01",
        unidad: "T-01",
        posicion: "Eje 1 Izquierda",
        km: 0,
        responsable: "Taller Mecánico",
      },
      {
        id: "h3",
        fecha: new Date("2024-01-10"),
        tipo: "inspeccion",
        descripcion: "Inspección rutinaria - 14mm",
        km: 45000,
        responsable: "Inspector",
      },
      {
        id: "h4",
        fecha: new Date("2024-06-05"),
        tipo: "reparacion",
        descripcion: "Reparación pinchazo",
        costo: 700,
        km: 70000,
        responsable: "Taller Mecánico",
      },
    ],
  },
  {
    id: "LL-002",
    codigoInterno: "LL-002",
    marca: "Bridgestone",
    modelo: "R297",
    medida: "295/80R22.5",
    dot: "2423",
    unidadActual: "T-01",
    posicion: "Eje 1 Derecha",
    estado: "usado",
    estadoFisico: "buena",
    profundidadActual: 11,
    profundidadOriginal: 18,
    kmRecorridos: 92000,
    fechaCompra: new Date("2023-05-10"),
    precioCompra: 8200,
    costoAcumulado: 8200,
    proveedor: "Bridgestone México",
    historial: [
      {
        id: "h1",
        fecha: new Date("2023-05-10"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 8200,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2023-05-15"),
        tipo: "montaje",
        descripcion: "Montaje en T-01",
        unidad: "T-01",
        posicion: "Eje 1 Derecha",
        km: 0,
        responsable: "Taller Mecánico",
      },
    ],
  },
  {
    id: "LL-003",
    codigoInterno: "LL-003",
    marca: "Goodyear",
    modelo: "KMAX D",
    medida: "295/80R22.5",
    dot: "1524",
    unidadActual: "T-02",
    posicion: "Eje 2 Izquierda",
    estado: "usado",
    estadoFisico: "regular",
    profundidadActual: 7,
    profundidadOriginal: 18,
    kmRecorridos: 145000,
    fechaCompra: new Date("2022-12-01"),
    precioCompra: 7800,
    costoAcumulado: 9500,
    proveedor: "Goodyear Comercial",
    historial: [
      {
        id: "h1",
        fecha: new Date("2022-12-01"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 7800,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2022-12-05"),
        tipo: "montaje",
        descripcion: "Montaje en T-02",
        unidad: "T-02",
        posicion: "Eje 1 Izquierda",
        km: 0,
        responsable: "Taller Mecánico",
      },
      {
        id: "h3",
        fecha: new Date("2023-08-15"),
        tipo: "rotacion",
        descripcion: "Rotación a Eje 2",
        unidad: "T-02",
        posicion: "Eje 2 Izquierda",
        km: 95000,
        responsable: "Taller Mecánico",
      },
      {
        id: "h4",
        fecha: new Date("2024-02-20"),
        tipo: "reparacion",
        descripcion: "Reparación lateral",
        costo: 1200,
        km: 120000,
        responsable: "Taller Externo",
      },
      {
        id: "h5",
        fecha: new Date("2024-06-01"),
        tipo: "renovado",
        descripcion: "Renovado en planta",
        costo: 500,
        km: 140000,
        responsable: "Renovadora XYZ",
      },
    ],
  },
  {
    id: "LL-004",
    codigoInterno: "LL-004",
    marca: "Continental",
    modelo: "HDL2 DL+",
    medida: "295/80R22.5",
    dot: "0824",
    unidadActual: null,
    posicion: null,
    estado: "nuevo",
    estadoFisico: "buena",
    profundidadActual: 18,
    profundidadOriginal: 18,
    kmRecorridos: 0,
    fechaCompra: new Date("2024-08-01"),
    precioCompra: 9200,
    costoAcumulado: 9200,
    proveedor: "Continental México",
    historial: [
      {
        id: "h1",
        fecha: new Date("2024-08-01"),
        tipo: "compra",
        descripcion: "Compra inicial - Stock",
        costo: 9200,
        responsable: "Admin",
      },
    ],
  },
  {
    id: "LL-005",
    codigoInterno: "LL-005",
    marca: "Michelin",
    modelo: "XDA5+",
    medida: "295/80R22.5",
    dot: "3522",
    unidadActual: "T-03",
    posicion: "Eje 3 Izquierda Ext",
    estado: "usado",
    estadoFisico: "mala",
    profundidadActual: 3,
    profundidadOriginal: 18,
    kmRecorridos: 210000,
    fechaCompra: new Date("2022-09-01"),
    precioCompra: 8800,
    costoAcumulado: 11500,
    proveedor: "Michelin México",
    historial: [
      {
        id: "h1",
        fecha: new Date("2022-09-01"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 8800,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2022-09-05"),
        tipo: "montaje",
        descripcion: "Montaje en T-01",
        unidad: "T-01",
        posicion: "Eje 1 Izquierda",
        km: 0,
        responsable: "Taller Mecánico",
      },
      {
        id: "h3",
        fecha: new Date("2023-03-15"),
        tipo: "rotacion",
        descripcion: "Rotación a T-02",
        unidad: "T-02",
        posicion: "Eje 2 Derecha",
        km: 80000,
        responsable: "Taller Mecánico",
      },
      {
        id: "h4",
        fecha: new Date("2023-10-20"),
        tipo: "reparacion",
        descripcion: "Reparación múltiple",
        costo: 1500,
        km: 140000,
        responsable: "Taller Externo",
      },
      {
        id: "h5",
        fecha: new Date("2024-04-10"),
        tipo: "rotacion",
        descripcion: "Rotación a T-03 Eje 3",
        unidad: "T-03",
        posicion: "Eje 3 Izquierda Ext",
        km: 180000,
        responsable: "Taller Mecánico",
      },
      {
        id: "h6",
        fecha: new Date("2024-07-01"),
        tipo: "renovado",
        descripcion: "Renovado emergencia",
        costo: 1200,
        km: 200000,
        responsable: "Renovadora XYZ",
      },
    ],
  },
  {
    id: "LL-006",
    codigoInterno: "LL-006",
    marca: "Pirelli",
    modelo: "TR01",
    medida: "295/80R22.5",
    dot: "1223",
    unidadActual: null,
    posicion: null,
    estado: "renovado",
    estadoFisico: "buena",
    profundidadActual: 14,
    profundidadOriginal: 16,
    kmRecorridos: 0,
    fechaCompra: new Date("2023-03-15"),
    precioCompra: 7500,
    costoAcumulado: 10200,
    proveedor: "Pirelli Industrial",
    historial: [
      {
        id: "h1",
        fecha: new Date("2023-03-15"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 7500,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2023-03-20"),
        tipo: "montaje",
        descripcion: "Montaje en T-04",
        unidad: "T-04",
        posicion: "Eje 1 Izquierda",
        km: 0,
        responsable: "Taller Mecánico",
      },
      {
        id: "h3",
        fecha: new Date("2024-05-01"),
        tipo: "desmontaje",
        descripcion: "Desmontaje para renovado",
        unidad: "T-04",
        km: 120000,
        responsable: "Taller Mecánico",
      },
      {
        id: "h4",
        fecha: new Date("2024-05-15"),
        tipo: "renovado",
        descripcion: "Renovado completo",
        costo: 2700,
        responsable: "Renovadora ABC",
      },
    ],
  },
  {
    id: "LL-007",
    codigoInterno: "LL-007",
    marca: "Hankook",
    modelo: "DL10+",
    medida: "11R24.5",
    dot: "2024",
    unidadActual: "R-01",
    posicion: "Eje 1 Izquierda",
    estado: "nuevo",
    estadoFisico: "buena",
    profundidadActual: 17,
    profundidadOriginal: 18,
    kmRecorridos: 15000,
    fechaCompra: new Date("2024-05-01"),
    precioCompra: 6800,
    costoAcumulado: 6800,
    proveedor: "Hankook México",
    historial: [
      {
        id: "h1",
        fecha: new Date("2024-05-01"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 6800,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2024-05-05"),
        tipo: "montaje",
        descripcion: "Montaje en R-01",
        unidad: "R-01",
        posicion: "Eje 1 Izquierda",
        km: 0,
        responsable: "Taller Mecánico",
      },
    ],
  },
  {
    id: "LL-008",
    codigoInterno: "LL-008",
    marca: "Yokohama",
    modelo: "TY517",
    medida: "11R24.5",
    dot: "4823",
    unidadActual: "R-02",
    posicion: "Eje 2 Derecha",
    estado: "usado",
    estadoFisico: "regular",
    profundidadActual: 9,
    profundidadOriginal: 18,
    kmRecorridos: 98000,
    fechaCompra: new Date("2023-11-01"),
    precioCompra: 7200,
    costoAcumulado: 7200,
    proveedor: "Yokohama Industrial",
    historial: [
      {
        id: "h1",
        fecha: new Date("2023-11-01"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 7200,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2023-11-05"),
        tipo: "montaje",
        descripcion: "Montaje en R-02",
        unidad: "R-02",
        posicion: "Eje 2 Derecha",
        km: 0,
        responsable: "Taller Mecánico",
      },
    ],
  },
  {
    id: "LL-009",
    codigoInterno: "LL-009",
    marca: "Bridgestone",
    modelo: "M749",
    medida: "295/80R22.5",
    dot: "2622",
    unidadActual: null,
    posicion: null,
    estado: "desecho",
    estadoFisico: "mala",
    profundidadActual: 1,
    profundidadOriginal: 18,
    kmRecorridos: 280000,
    fechaCompra: new Date("2022-06-01"),
    precioCompra: 8000,
    costoAcumulado: 14500,
    proveedor: "Bridgestone México",
    historial: [
      {
        id: "h1",
        fecha: new Date("2022-06-01"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 8000,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2022-06-05"),
        tipo: "montaje",
        descripcion: "Montaje en T-05",
        unidad: "T-05",
        posicion: "Eje 1 Izquierda",
        km: 0,
        responsable: "Taller Mecánico",
      },
      {
        id: "h3",
        fecha: new Date("2023-02-01"),
        tipo: "rotacion",
        descripcion: "Rotación Eje 2",
        unidad: "T-05",
        posicion: "Eje 2 Izquierda",
        km: 90000,
        responsable: "Taller Mecánico",
      },
      {
        id: "h4",
        fecha: new Date("2023-08-15"),
        tipo: "reparacion",
        descripcion: "Reparación banda",
        costo: 2000,
        km: 150000,
        responsable: "Taller Externo",
      },
      {
        id: "h5",
        fecha: new Date("2024-01-10"),
        tipo: "renovado",
        descripcion: "Renovado",
        costo: 2500,
        km: 200000,
        responsable: "Renovadora ABC",
      },
      {
        id: "h6",
        fecha: new Date("2024-06-01"),
        tipo: "desmontaje",
        descripcion: "Desmontaje final",
        unidad: "T-05",
        km: 280000,
        responsable: "Taller Mecánico",
      },
      {
        id: "h7",
        fecha: new Date("2024-06-05"),
        tipo: "desecho",
        descripcion: "Enviada a desecho - desgaste total",
        costo: 2000,
        responsable: "Admin",
      },
    ],
  },
  {
    id: "LL-010",
    codigoInterno: "LL-010",
    marca: "Continental",
    modelo: "HDL2 ECO+",
    medida: "295/80R22.5",
    dot: "0924",
    unidadActual: null,
    posicion: null,
    estado: "nuevo",
    estadoFisico: "buena",
    profundidadActual: 18,
    profundidadOriginal: 18,
    kmRecorridos: 0,
    fechaCompra: new Date("2024-09-01"),
    precioCompra: 9500,
    costoAcumulado: 9500,
    proveedor: "Continental México",
    historial: [
      {
        id: "h1",
        fecha: new Date("2024-09-01"),
        tipo: "compra",
        descripcion: "Compra inicial - Stock",
        costo: 9500,
        responsable: "Admin",
      },
    ],
  },
  {
    id: "LL-011",
    codigoInterno: "LL-011",
    marca: "Michelin",
    modelo: "X Multi D",
    medida: "11R22.5",
    dot: "3024",
    unidadActual: "T-04",
    posicion: "Repuesto",
    estado: "nuevo",
    estadoFisico: "buena",
    profundidadActual: 18,
    profundidadOriginal: 18,
    kmRecorridos: 0,
    fechaCompra: new Date("2024-07-15"),
    precioCompra: 8900,
    costoAcumulado: 8900,
    proveedor: "Michelin México",
    historial: [
      {
        id: "h1",
        fecha: new Date("2024-07-15"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 8900,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2024-07-20"),
        tipo: "montaje",
        descripcion: "Montaje como repuesto T-04",
        unidad: "T-04",
        posicion: "Repuesto",
        km: 0,
        responsable: "Taller Mecánico",
      },
    ],
  },
  {
    id: "LL-012",
    codigoInterno: "LL-012",
    marca: "Goodyear",
    modelo: "KMAX S",
    medida: "295/80R22.5",
    dot: "1824",
    unidadActual: "T-05",
    posicion: "Eje 1 Izquierda",
    estado: "usado",
    estadoFisico: "buena",
    profundidadActual: 15,
    profundidadOriginal: 18,
    kmRecorridos: 42000,
    fechaCompra: new Date("2024-04-01"),
    precioCompra: 8100,
    costoAcumulado: 8100,
    proveedor: "Goodyear Comercial",
    historial: [
      {
        id: "h1",
        fecha: new Date("2024-04-01"),
        tipo: "compra",
        descripcion: "Compra inicial",
        costo: 8100,
        responsable: "Admin",
      },
      {
        id: "h2",
        fecha: new Date("2024-04-05"),
        tipo: "montaje",
        descripcion: "Montaje en T-05",
        unidad: "T-05",
        posicion: "Eje 1 Izquierda",
        km: 0,
        responsable: "Taller Mecánico",
      },
    ],
  },
];
