"""Creacion inicial de tablas

Revision ID: 0fce0a63f1ac
Revises: 
Create Date: 2026-01-28 23:38:30.300209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fce0a63f1ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('regimen_fiscal', sa.String(length=10), nullable=True),
    sa.Column('uso_cfdi', sa.String(length=10), nullable=True),
    sa.Column('contacto_principal', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion_fiscal', sa.Text(), nullable=True),
    sa.Column('codigo_postal_fiscal', sa.String(length=10), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'PENDIENTE', 'INCOMPLETO', name='clientstatus'), nullable=True),
    sa.Column('contrato_url', sa.String(length=500), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('permisos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('units',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('numero_economico', sa.String(length=20), nullable=False),
    sa.Column('placas', sa.String(length=15), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('SENCILLO', 'FULL', 'RABON', name='unittype'), nullable=False),
    sa.Column('status', sa.Enum('DISPONIBLE', 'EN_RUTA', 'MANTENIMIENTO', 'BLOQUEADO', name='unitstatus'), nullable=True),
    sa.Column('documentos_vencidos', sa.Integer(), nullable=True),
    sa.Column('llantas_criticas', sa.Integer(), nullable=True),
    sa.Column('seguro_vence', sa.Date(), nullable=True),
    sa.Column('verificacion_vence', sa.Date(), nullable=True),
    sa.Column('permiso_sct_vence', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_economico'),
    sa.UniqueConstraint('placas')
    )
    op.create_table('operators',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_type', sa.String(length=5), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('medical_check_expiry', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', 'VACACIONES', 'INCAPACIDAD', name='operatorstatus'), nullable=True),
    sa.Column('assigned_unit_id', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('sub_clients',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('tipo_operacion', sa.Enum('IMPORTACION', 'EXPORTACION', 'NACIONAL', name='operationtype'), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('horario_recepcion', sa.String(length=50), nullable=True),
    sa.Column('estatus', sa.String(length=20), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=True),
    sa.Column('requiere_contrato', sa.Boolean(), nullable=True),
    sa.Column('convenio_especial', sa.Boolean(), nullable=True),
    sa.Column('contrato_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('preferencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tariffs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('sub_client_id', sa.String(length=50), nullable=False),
    sa.Column('nombre_ruta', sa.String(length=200), nullable=False),
    sa.Column('tipo_unidad', sa.Enum('SENCILLO', 'FULL', 'RABON', name='unittype'), nullable=False),
    sa.Column('tarifa_base', sa.Float(), nullable=False),
    sa.Column('costo_casetas', sa.Float(), nullable=True),
    sa.Column('moneda', sa.Enum('MXN', 'USD', name='currency'), nullable=True),
    sa.Column('vigencia', sa.Date(), nullable=False),
    sa.Column('estatus', sa.Enum('ACTIVA', 'VENCIDA', 'POR_VENCER', name='tariffstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.Column('sub_client_id', sa.String(length=50), nullable=False),
    sa.Column('unit_id', sa.String(length=50), nullable=False),
    sa.Column('operator_id', sa.String(length=50), nullable=False),
    sa.Column('tariff_id', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('route_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('CREADO', 'EN_TRANSITO', 'DETENIDO', 'RETRASO', 'ENTREGADO', 'CERRADO', 'ACCIDENTE', name='tripstatus'), nullable=True),
    sa.Column('tarifa_base', sa.Float(), nullable=False),
    sa.Column('costo_casetas', sa.Float(), nullable=True),
    sa.Column('anticipo_casetas', sa.Float(), nullable=True),
    sa.Column('anticipo_viaticos', sa.Float(), nullable=True),
    sa.Column('anticipo_combustible', sa.Float(), nullable=True),
    sa.Column('otros_anticipos', sa.Float(), nullable=True),
    sa.Column('saldo_operador', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('last_location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['sub_client_id'], ['sub_clients.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('event', sa.String(length=500), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_timeline_events')
    op.drop_table('trips')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sub_clients')
    op.drop_table('operators')
    op.drop_table('units')
    op.drop_table('system_configs')
    op.drop_table('roles')
    op.drop_table('clients')
    # ### end Alembic commands ###
