import { PurchaseOrder, Supplier, InventoryItem } from './types';

export const mockSuppliers: Supplier[] = [
  { id: 'sup-1', nombre: 'Refaccionaria del Norte', rfc: 'RFN850101ABC', tipo: 'refacciones' },
  { id: 'sup-2', nombre: 'Llantas Michelin México', rfc: 'LMM920315DEF', tipo: 'refacciones' },
  { id: 'sup-3', nombre: 'Taller Mecánico Central', rfc: 'TMC880712GHI', tipo: 'servicios' },
  { id: 'sup-4', nombre: 'Renovadora de Llantas ABC', rfc: 'RLA950420JKL', tipo: 'servicios' },
  { id: 'sup-5', nombre: 'Oficinas y Papelería SA', rfc: 'OPS780930MNO', tipo: 'general' },
  { id: 'sup-6', nombre: 'Servicios de Limpieza Pro', rfc: 'SLP010215PQR', tipo: 'general' },
  { id: 'sup-7', nombre: 'Lubricantes Pemex', rfc: 'LPX650101STU', tipo: 'refacciones' },
];

export const mockInventoryItems: InventoryItem[] = [
  { id: 'inv-1', codigo: 'REF-001', nombre: 'Filtro de Aceite Motor', unidad: 'PZA', precioPromedio: 450, stockActual: 15, stockMinimo: 10 },
  { id: 'inv-2', codigo: 'REF-002', nombre: 'Filtro de Aire', unidad: 'PZA', precioPromedio: 380, stockActual: 8, stockMinimo: 10 },
  { id: 'inv-3', codigo: 'REF-003', nombre: 'Filtro de Combustible', unidad: 'PZA', precioPromedio: 520, stockActual: 12, stockMinimo: 8 },
  { id: 'inv-4', codigo: 'REF-004', nombre: 'Aceite Motor 15W40 (20L)', unidad: 'CUBT', precioPromedio: 2800, stockActual: 5, stockMinimo: 8 },
  { id: 'inv-5', codigo: 'REF-005', nombre: 'Balatas Freno Delantero', unidad: 'JGO', precioPromedio: 3200, stockActual: 4, stockMinimo: 6 },
  { id: 'inv-6', codigo: 'REF-006', nombre: 'Balatas Freno Trasero', unidad: 'JGO', precioPromedio: 2900, stockActual: 3, stockMinimo: 6 },
  { id: 'inv-7', codigo: 'REF-007', nombre: 'Foco Cuarzo H4', unidad: 'PZA', precioPromedio: 180, stockActual: 20, stockMinimo: 15 },
  { id: 'inv-8', codigo: 'REF-008', nombre: 'Manguera Radiador', unidad: 'PZA', precioPromedio: 850, stockActual: 6, stockMinimo: 4 },
  { id: 'inv-9', codigo: 'REF-009', nombre: 'Anticongelante (4L)', unidad: 'GAL', precioPromedio: 320, stockActual: 10, stockMinimo: 8 },
  { id: 'inv-10', codigo: 'REF-010', nombre: 'Limpiador de Frenos', unidad: 'LTA', precioPromedio: 145, stockActual: 25, stockMinimo: 12 },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-1',
    folio: 'OC-2024-001',
    tipo: 'compra',
    proveedorId: 'sup-1',
    proveedorNombre: 'Refaccionaria del Norte',
    solicitante: 'Juan Pérez (Mantenimiento)',
    fechaCreacion: new Date('2024-01-10'),
    fechaRequerida: new Date('2024-01-15'),
    centroCostos: 'mantenimiento',
    items: [
      { id: 'i1', descripcion: 'Filtro de Aceite Motor', cantidad: 10, unidad: 'PZA', precioUnitario: 450, subtotal: 4500 },
      { id: 'i2', descripcion: 'Filtro de Aire', cantidad: 10, unidad: 'PZA', precioUnitario: 380, subtotal: 3800 },
    ],
    subtotal: 8300,
    iva: 1328,
    total: 9628,
    moneda: 'MXN',
    estatus: 'recibida',
    fechaAprobacion: new Date('2024-01-11'),
    aprobadoPor: 'Gerente Operaciones',
    fechaRecepcion: new Date('2024-01-14'),
    recepcionCompleta: true,
    convertidoACxP: true,
    cxpId: 'cxp-001',
  },
  {
    id: 'po-2',
    folio: 'OS-2024-001',
    tipo: 'servicio',
    proveedorId: 'sup-3',
    proveedorNombre: 'Taller Mecánico Central',
    solicitante: 'Carlos Rodríguez (Flota)',
    fechaCreacion: new Date('2024-01-12'),
    fechaRequerida: new Date('2024-01-20'),
    centroCostos: 'mantenimiento',
    items: [],
    descripcionServicio: 'Reparación de transmisión completa para unidad T-03. Incluye mano de obra y refacciones menores.',
    subtotal: 28000,
    iva: 4480,
    total: 32480,
    moneda: 'MXN',
    estatus: 'aprobada',
    fechaAprobacion: new Date('2024-01-13'),
    aprobadoPor: 'Director General',
    convertidoACxP: false,
  },
  {
    id: 'po-3',
    folio: 'OC-2024-002',
    tipo: 'compra',
    proveedorId: 'sup-7',
    proveedorNombre: 'Lubricantes Pemex',
    solicitante: 'Juan Pérez (Mantenimiento)',
    fechaCreacion: new Date('2024-01-15'),
    fechaRequerida: new Date('2024-01-22'),
    centroCostos: 'mantenimiento',
    items: [
      { id: 'i1', descripcion: 'Aceite Motor 15W40 (20L)', cantidad: 15, unidad: 'CUBT', precioUnitario: 2800, subtotal: 42000 },
    ],
    subtotal: 42000,
    iva: 6720,
    total: 48720,
    moneda: 'MXN',
    estatus: 'pendiente_aprobacion',
    convertidoACxP: false,
  },
  {
    id: 'po-4',
    folio: 'GI-2024-001',
    tipo: 'gasto_indirecto',
    proveedorId: 'sup-5',
    proveedorNombre: 'Oficinas y Papelería SA',
    solicitante: 'María García (Administración)',
    fechaCreacion: new Date('2024-01-08'),
    fechaRequerida: new Date('2024-01-10'),
    centroCostos: 'administrativo',
    categoriaIndirecto: 'papeleria',
    items: [
      { id: 'i1', descripcion: 'Resma Papel Bond', cantidad: 20, unidad: 'PQT', precioUnitario: 120, subtotal: 2400 },
      { id: 'i2', descripcion: 'Tóner Impresora HP', cantidad: 4, unidad: 'PZA', precioUnitario: 850, subtotal: 3400 },
    ],
    subtotal: 5800,
    iva: 928,
    total: 6728,
    moneda: 'MXN',
    estatus: 'recibida',
    fechaAprobacion: new Date('2024-01-08'),
    aprobadoPor: 'Gerente Administrativo',
    fechaRecepcion: new Date('2024-01-09'),
    recepcionCompleta: true,
    convertidoACxP: false,
  },
  {
    id: 'po-5',
    folio: 'OC-2024-003',
    tipo: 'compra',
    proveedorId: 'sup-1',
    proveedorNombre: 'Refaccionaria del Norte',
    solicitante: 'Pedro López (Almacén)',
    fechaCreacion: new Date('2024-01-18'),
    fechaRequerida: new Date('2024-01-25'),
    centroCostos: 'mantenimiento',
    items: [
      { id: 'i1', descripcion: 'Balatas Freno Delantero', cantidad: 8, unidad: 'JGO', precioUnitario: 3200, subtotal: 25600 },
      { id: 'i2', descripcion: 'Balatas Freno Trasero', cantidad: 8, unidad: 'JGO', precioUnitario: 2900, subtotal: 23200 },
    ],
    subtotal: 48800,
    iva: 7808,
    total: 56608,
    moneda: 'MXN',
    estatus: 'borrador',
    convertidoACxP: false,
  },
];

// Generate next folio
export const generateFolio = (tipo: 'compra' | 'servicio' | 'gasto_indirecto'): string => {
  const prefix = tipo === 'compra' ? 'OC' : tipo === 'servicio' ? 'OS' : 'GI';
  const year = new Date().getFullYear();
  const num = Math.floor(Math.random() * 900) + 100;
  return `${prefix}-${year}-${num}`;
};
